export const SET_TOKEN = "SET_TOKEN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UNSET_CURRENT_USER = "UNSET_CURRENT_USER";
export const GET_CLIENTS = "GET_CLIENTS";
export const USERS_ERROR = "USERS_ERROR";
export const GET_CLIENTS_TRAITS = "GET_CLIENTS_TRAITS"
